[[redirects]]
  from = "/api/trucky/*"
  to = "https://e.truckyapp.com/api/v1/company/41407/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/trucky-user/*"
  to = "https://e.truckyapp.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/mdcdev/*"
  to = "https://api.mdcdev.me/v2/peruserver/trucky/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/osrm/*"
  to = "https://router.project-osrm.org/route/v1/driving/:splat"
  status = 200
  force = true
